# camera and checkerboard data for the gazebo youbot simulation with the provided checkerboard model

camera:
  fx: 425.391974081817
  fy: 426.242423913828
  cx: 366.443714837012
  cy: 213.600885097216
  
hec:
  checkerboard:
    squares_per_column: 6
    squares_per_row: 8
    square_size: 0.073 # m