# camera and checkerboard data for the gazebo youbot simulation with the provided checkerboard model
  
hec:
  checkerboard:
    squares_per_column: 6
    squares_per_row: 8
    square_size: 0.05 # [m]