joints:
  - arm_joint_4
  - arm_joint_3
  - arm_joint_2
  - arm_joint_1
  #- arm_joint_5
joint_space:
  arm_joint_1: {lower_limit: 0.011, upper_limit: 5.840, step_size: 0.05}
  arm_joint_2: {lower_limit: 0.011, upper_limit: 2.617, step_size: 0.1}
  arm_joint_3: {lower_limit: -5.026, upper_limit: -0.016, step_size: 0.1}
  arm_joint_4: {lower_limit: 0.023, upper_limit: 3.429, step_size: 0.05}
  arm_joint_5: {lower_limit: 0.111, upper_limit: 5.641, step_size: 0.1}
moveit_group_name: arm
estimation_type: dual_quaternion # not used yet
robot_base_frame: arm_link_0
hand_frame: arm_link_5
hec_estimate:
  translation:
    x:0
    y:0.04
    z:0
  rotation:
    x:0
    y:0
    z:0.707
    w:0.707
trusting_threshold: 4 # nr of measurements until hec estimate might be used (if hec_estimate isn't set)

image_border_tolerance: 20
pattern_safety_distance: 0.2 # minimal distance the camera coordinate system origin must have from calculated pattern positions[m]